### ISSUE TITLE
The living mage robes are broken

### ISSUE THREAD

**Issue by ummpasta** [dphaldes/Tome-of-Blood#3]
![Screenshot 2023-09-29 100959](https://github.com/mystchonky/Tome-of-Blood/assets/100769797/72d8a325-063c-440c-a9b7-ebcb0d539d16)
They dont give any effects of the living armor like healthy's extra hp

**Comment by dphaldes** [comment]
Thanks for reporting! I will investigate!

**Comment by dphaldes** [comment]
I have just released v0.1.2 with a fix. Let me know if that fixes it! :)
