### ISSUE TITLE
Sentient Harm Crashes Server

### ISSUE THREAD

**Issue by nekhs** [dphaldes/Tome-of-Blood#4]
[latest(1).log](https://github.com/mystchonky/Tome-of-Blood/files/12835931/latest.1.log)

So basically I miss a lot with projectile -> Sentient Harm and even without amplify involved it crashes the server pretty reliably.

Haven't really tried touch or self. 

If it helps, I have upgraded my living mage robes to tier 2 and am using a mage spellbook. Believe I had these upgrades when I last ran into this issue.

Thanks for your time!

**Comment by dphaldes** [comment]
Thanks for the report! I will look into it! :)

**Comment by dphaldes** [comment]
I have made a new release v.0.2.0 with the fix!
