### ISSUE TITLE
Sentient Wrath Crashes Server

### ISSUE THREAD

**Issue by aqua-air** [dphaldes/Tome-of-Blood#5]
Again on Sanctum Network, sorry! 
Sanctum Network V 5.88 
Tome of Blood V 0.4.2
Forge 47.2.5 
MC 1.20.1 

Player said sentient wrath is still the issue
Crash report: 
https://mclo.gs/kNHh2Xd

**Comment by dphaldes** [comment]
That's an easy fix. I will push an update soon! Thanks for reporting :)

**Comment by dphaldes** [comment]
v0.4.3 should fix this :)
