### ISSUE TITLE
Heretic Armor ignores the Living Evolution ritual

### ISSUE THREAD

**Issue by dinckelman** [dphaldes/Tome-of-Blood#6]
Typically, the ritual of Living Evolution is supposed to boost your chestplate's capacity from 100 to 300, however it appears that the Heretic armor completely ignores the ritual

Versions affected:
tomeofblood-1.20.1-0.4.3 and older
bloodmagic-1.20.1-3.3.2-44 and older

**Comment by dphaldes** [comment]
Hello! Thanks for reporting the issue.
I cannot seem to replicate this in my dev environment. Are you sure the ritual is active ?
Can you provide more details like the modpack used?

**Comment by dinckelman** [comment]
It appears that something was wrong with the ritual itself. I've attempted to reproduce this with the regular armor first today, which has also not worked, however after remaking the ritual, it started working as intended. I suppose we can consider this closed

**Comment by dphaldes** [comment]
No worries. Feel free to reopen or create new issues if you face any difficulty :)
