### ISSUE TITLE
Modrinth latest 1.20.1 version depends on "Unknown Project"

### ISSUE THREAD

**Issue by PinkDisorder** [dphaldes/Tome-of-Blood#9]
As the title says, [Tome of Blood 1.20.1-0.4.4](https://modrinth.com/mod/tome-of-blood-rebirth/version/1.20.1-0.4.4) has "Unknown Project" listed as a required dependency, which makes it impossible to pull in the mod via the Prism Launcher.

**Comment by dphaldes** [comment]
Fixed! Thanks for informing!
